### ISSUE TITLE
Api doesn't work

### ISSUE THREAD

**Issue by delfme** [MusilyApp/dart_ytmusic_api#1]
Hello, I'm running this code but get no results. It also throws no error, so it is hard to debug without looking into the low level code. Can you please double check that the methods work with no issues on your side?
```
 final client = YTMusic();
  await client.initialize();
  youtubeSongs = await YouTubeMusicAPI.client.search(query);
  print("DEBUG youtubeSongs $youtubeSongs");
```

**Comment by FelipeYslaoker** [comment]
Hi! It works perfectly. 
![image](https://github.com/user-attachments/assets/b7b4c903-062d-411d-b944-cca7ee54aa33)

**Comment by FelipeYslaoker** [comment]
Hello, this issue was fixed.

**Comment by FelipeYslaoker** [comment]
Could you take a look at my application, for which this plugin is dedicated, and see how these challenges could potentially be overcome?  
You can find the source code here: [Musily GitHub Repository](https://github.com/MusilyApp/musily).  

Thank you!

**Comment by delfme** [comment]
Your app looks great! 👏 I couldnt go through code coz Im our travelling. 

For point 1) I take for granted that you intercept ad and cut it off. But is this consistent?
For point 2) I guess it is something like that https://stackoverflow.com/a/64118047  

So the only critical part is Google shutting down apps if they generate huge traffic through this approach. What's your thoughts?

**Comment by FelipeYslaoker** [comment]
1) My app has no ads to be cut
2) Not aware of that, but as my app has no server, the only way to be down is deleting the repository 

😄

**Comment by delfme** [comment]
😄 yea, but I meant apps published on the stores. They will shut them down.

**Comment by FelipeYslaoker** [comment]
In fact the app isn't able to be published on Google Play. About Apple, I think it's
